django/alhuilecine/alhuilecine/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^', include('siteweb.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

django/alhuilecine/siteweb/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url
from siteweb import views
from django.contrib.auth.forms import UserCreationForm
from django.views import generic
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

urlpatterns = patterns('',
    url(r'^$', views.index, name = 'index'),
    (r'^accounts/login/$', 'django.contrib.auth.views.login', {'template_name': 'siteweb/login.html'}),
    (r'^accounts/logout/$', 'django.contrib.auth.views.logout_then_login', {}),
    url(r'^accounts/register/$', (generic.CreateView.as_view(model = User, get_success_url = lambda: reverse('django.contrib.auth.views.logout_then_login'), form_class=UserCreationForm, template_name="siteweb/register.html")), name='accounts/register'),
    url(r'^films/$', views.FilmListView.as_view(), name = 'films'),
    url(r'^film/(?P<pk>\d+)/$', views.FilmDetailView.as_view(), name = 'film'),
    url(r'^ajouter/film/$', views.FilmCreateView.as_view(), name = 'ajouter/film'),
    url(r'^mettreajour/film/(?P<pk>\d+)/$', views.FilmUpdateView.as_view(), name = 'mettreajour/film'),
    url(r'^supprimer/film/(?P<pk>\d+)/$', views.FilmDeleteView.as_view(), name = 'supprimer/film'),
    url(r'^ajouter/message/(?P<forumId>\d+)/(?P<messageId>\d+)/$', views.MessageCreateView.as_view(), name = 'ajouter/message'),
    url(r'^ajouter/message/(?P<forumId>\d+)/$', views.MessageCreateView.as_view(), name = 'ajouter/message'),
    url(r'^artistes/$', views.ArtisteListView.as_view(), name = 'artistes'),
    url(r'^artiste/(?P<pk>\d+)/$', views.ArtisteDetailView.as_view(), name = 'artiste'),
    url(r'^ajouter/artiste/$', views.ArtisteCreateView.as_view(), name = 'ajouter/artiste'),
    url(r'^mettreajour/artiste/(?P<pk>\d+)/$', views.ArtisteUpdateView.as_view(), name = 'mettreajour/artiste'),
    url(r'^supprimer/artiste/(?P<pk>\d+)/$', views.ArtisteDeleteView.as_view(), name = 'supprimer/artiste'),
    url(r'^genres/$', views.GenreListView.as_view(), name = 'genres'),
    url(r'^genre/(?P<pk>\d+)/$', views.GenreDetailView.as_view(), name = 'genre'),
    url(r'^ajouter/genre/$', views.GenreCreateView.as_view(), name = 'ajouter/genre'),
    url(r'^mettreajour/genre/(?P<pk>\d+)/$', views.GenreUpdateView.as_view(), name = 'mettreajour/genre'),
    url(r'^supprimer/genre/(?P<pk>\d+)/$', views.GenreDeleteView.as_view(), name = 'supprimer/genre'),
    url(r'^nationalites/$', views.NationaliteListView.as_view(), name = 'nationalites'),
    url(r'^nationalite/(?P<pk>\d+)/$', views.NationaliteDetailView.as_view(), name = 'nationalite'),
    url(r'^ajouter/nationalite/$', views.NationaliteCreateView.as_view(), name = 'ajouter/nationalite'),
    url(r'^mettreajour/nationalite/(?P<pk>\d+)/$', views.NationaliteUpdateView.as_view(), name = 'mettreajour/nationalite'),
    url(r'^supprimer/nationalite/(?P<pk>\d+)/$', views.NationaliteDeleteView.as_view(), name = 'supprimer/nationalite'),
    url(r'^personnages/$', views.PersonnageListView.as_view(), name = 'personnages'),
    url(r'^personnage/(?P<pk>\d+)/$', views.PersonnageDetailView.as_view(), name = 'personnage'),
    url(r'^ajouter/personnage/$', views.PersonnageCreateView.as_view(), name = 'ajouter/personnage'),
    url(r'^mettreajour/personnage/(?P<pk>\d+)/$', views.PersonnageUpdateView.as_view(), name = 'mettreajour/personnage'),
    url(r'^supprimer/personnage/(?P<pk>\d+)/$', views.PersonnageDeleteView.as_view(), name = 'supprimer/personnage'),
    url(r'^incarnerpersonnages/$', views.IncarnerpersonnageListView.as_view(), name = 'incarnerpersonnages'),
    url(r'^ajouter/incarnerpersonnage/$', views.IncarnerpersonnageCreateView.as_view(), name = 'ajouter/incarnerpersonnage'),
    url(r'^mettreajour/incarnerpersonnage/(?P<pk>\d+)/$', views.IncarnerpersonnageUpdateView.as_view(), name = 'mettreajour/incarnerpersonnage'),
    url(r'^supprimer/incarnerpersonnage/(?P<pk>\d+)/$', views.IncarnerpersonnageDeleteView.as_view(), name = 'supprimer/incarnerpersonnage'),
    url(r'^ajouter/noter/(?P<filmId>\d+)/$', views.NoterCreateView.as_view(), name = 'ajouter/noter'),
    url(r'^mettreajour/noter/(?P<pk>\d+)/$', views.NoterUpdateView.as_view(), name = 'mettreajour/noter'),
    url(r'^recherche/', include('haystack.urls')),
)

django/alhuilecine/siteweb/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.db import models
from django.contrib.auth.models import User
from datetime import datetime

class Nationalite(models.Model):
    nom = models.CharField(max_length = 100, verbose_name = u"Intitulé")
    
    def __str__(self):
        return self.nom
        
    class Meta:
        ordering = ['nom']

class Artiste(models.Model):
    nom = models.CharField(max_length = 100, verbose_name = u"Nom")
    prenom = models.CharField(max_length = 100, blank = True, verbose_name = u"Prénom")
    datenaissance = models.DateField(blank = True, null = True, verbose_name = u"Date de naissance (AAAA-MM-JJ)")
    datemort = models.DateField(blank = True, null = True, verbose_name = u"Date de mort (AAAA-MM-JJ)")
    biographie = models.TextField(max_length = 3000, blank = True, verbose_name = u"Biographie")
    nationalites = models.ManyToManyField(Nationalite, verbose_name = u"Nationalités", help_text = "<br/>", blank = True)

    def __str__(self):
        return self.prenom + " " + self.nom
        
    class Meta:
        ordering = ['nom']
    
class Personnage(models.Model):
    nom = models.CharField(max_length = 100, verbose_name = "Nom")
    
    def __str__(self):
        return self.nom
        
    class Meta:
        ordering = ['nom']
    
class Genre(models.Model):
    nom = models.CharField(max_length = 100, verbose_name = u"Intitulé")
    
    def __str__(self):
        return self.nom
        
    class Meta:
        ordering = ['nom']
        
class Forum(models.Model):
    moderateur = models.ForeignKey(User, verbose_name = u"Modérateur")
    
    def __str__(self):
        return u"Forum " + str(self.id) + u" modere par " + str(self.moderateur)

class Note(models.Model):
    valeur = models.IntegerField(verbose_name = u"Note")
   
    def __str__(self):
        return u"Note de " + str(self.valeur)
    
class Film(models.Model):
    titre = models.CharField(max_length = 100, verbose_name = u"Film")
    datesortie = models.DateField(verbose_name = u"Date de sortie (AAAA-MM-JJ)")
    synopsis = models.TextField(max_length = 3000, blank = True, verbose_name = u"Synopsis")
    acteurs = models.ManyToManyField(Artiste, verbose_name = u"Acteurs", help_text = "<br/>", related_name = 'acteurs', blank = True)
    realisateurs = models.ManyToManyField(Artiste, verbose_name = u"Réalisateurs", help_text = "<br/>", related_name = 'realisateurs', blank = True)
    personnages = models.ManyToManyField(Personnage, through='Incarnerpersonnage', verbose_name = u"Personnages", help_text = "<br/>", blank = True)
    genres = models.ManyToManyField(Genre, verbose_name = u"Genres", help_text = "<br/>", blank = True)
    nationalites = models.ManyToManyField(Nationalite, verbose_name = u"Nationalités", help_text = "<br/>", blank = True)
    forum = models.OneToOneField(Forum, verbose_name = u"Forum", help_text = "<br/>")
	
    def __str__(self):
        return self.titre + " (" + str(self.datesortie.year) + ")"
        
    class Meta:
        ordering = ['titre']
    
class Incarnerpersonnage(models.Model):
    personnage = models.ForeignKey(Personnage)
    film = models.ForeignKey(Film)
    artiste = models.ForeignKey(Artiste)
    
    def __str__(self):
        return str(self.artiste) + u" incarne " + str(self.personnage) + " dans " + str(self.film)

class Message(models.Model):
    texte = models.TextField(max_length = 3000, verbose_name = u"Message")
    dateenvoi = models.DateTimeField(default=datetime.now)
    forum = models.ForeignKey(Forum)
    envoyeur = models.ForeignKey(User)
    enreponsea = models.ForeignKey('self', blank = True, null = True)
    
    def __str__(self):
        return u"Message du " + str(self.dateenvoi) + u" par " + self.envoyeur.username + u" sur le forum \"" + str(self.forum) + u"\" : \"" + self.texte + u"\""
        
    class Meta:
        ordering = ['-dateenvoi']

class Groupe(models.Model):
    nom = models.CharField(max_length = 100, verbose_name = u"Nom")
    prive = models.BooleanField(default = False)
    forum = models.OneToOneField(Forum, verbose_name = u"Forum", help_text = "<br/>")
    artistes = models.ManyToManyField(Artiste, verbose_name = u"Artistes", help_text = "<br/>", blank = True)
    films = models.ManyToManyField(Film, verbose_name = u"Films", help_text = "<br/>", blank = True)
    personnages = models.ManyToManyField(Personnage, verbose_name = u"Personnages", help_text = "<br/>", blank = True)
    genres = models.ManyToManyField(Genre, verbose_name = u"Genres", help_text = "<br/>", blank = True)
    nationalites = models.ManyToManyField(Nationalite, verbose_name = u"Nationalités", help_text = "<br/>", blank = True)
    
    def __str__(self):
        return u"Groupe " + (u"prive" if self.prive else u"public") + " \"" + self.nom + "\""

class Noter(models.Model):
    utilisateur = models.ForeignKey(User)
    film = models.ForeignKey(Film)
    note = models.ForeignKey(Note)
    
    def __str__(self):
        return str(self.utilisateur) + u" a note " + str(self.film) + u" : \"" + str(self.note) + u"\""

class Sondage(models.Model):
    question = models.CharField(max_length = 1000, verbose_name = u"Question")
    dateproposition = models.DateField()
    proposeur = models.ForeignKey(User)
    
    def __str__(self):
        return u"Sondage propose par " + str(self.proposeur) + u" le " + str(self.dateproposition) + u" : \"" + self.question + u"\""

class Optionsondage(models.Model):
    sondage = models.ForeignKey(Sondage, verbose_name = u"Option")
    texte = models.CharField(max_length = 1000)
    
    def __str__(self):
        return u"Option \"" + self.texte + u"\" dans le sondage " + str(self.sondage)

class Sondageconcernergroupe(models.Model):
    sondage = models.ForeignKey(Sondage)
    groupe = models.ForeignKey(Groupe)

    def __str__(self):
        return str(self.sondage) + u" concerne " + str(self.groupe)

class Votesondage(models.Model):
    voteur = models.ForeignKey(User)
    sondage = models.ForeignKey(Sondage)
    optionsondage = models.ForeignKey(Optionsondage)
    
    def __str__(self):
        return str(self.voteur) + u" a vote l'option " + str(self.optionsondage)

django/alhuilecine/siteweb/templates/siteweb/artistes.html
{% extends "siteweb/base.html" %}

{% block content %}

<h1>Artistes
    {% if user.is_authenticated %}
    <span style="font-size: 2.4rem">
        (
        <a href="{% url 'ajouter/artiste' %}">ajouter un artiste</a>
        )
    </span>
    {% endif %}
</h1>
<table class="u-full-width">
    <thead>
        <tr>
            <th>Nom</th>
            <th>Date de naissance</th>
            <th>Date de mort</th>
            <th>Biographie</th>
        </tr>
    </thead>
    <tbody>
        {% for artiste in artistes %}
        <tr>
            <th><a href="{% url 'artiste' artiste.id %}">{{ artiste.prenom }} {{ artiste.nom }}</a></th>
            <th>
                {% if artiste.datenaissance %}
                    {{ artiste.datenaissance }}
                {% endif %}
            </th>
            <th>
                {% if artiste.datemort %}
                    {{ artiste.datemort }}
                {% endif %}
            </th>
            <th class="u-half-width">{{ artiste.biographie }}</th>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

django/alhuilecine/siteweb/templates/siteweb/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
    <head>
        <title>À l'huile ciné !</title>
        <meta name="viewport" content="width=device-width, initial-scale=1"> <!-- For mobile -->
        <link href="//fonts.googleapis.com/css?family=Raleway:400,300,600" rel="stylesheet" type="text/css"> <!-- Font -->
        <link rel="stylesheet" href="{% static "normalize.css" %}">
        <link rel="stylesheet" href="{% static "skeleton.css" %}">
    </head>
    <body>
        <div class="container">
            <div class="row">
                <a href="{% url 'index' %}">
                <img src="{% static "baniere.png" %}" alt="Banière"/>
                </a>
            </div>
            <div class="row">
                <a href="{% url 'index' %}">Accueil</a>
                &bull;
                <a href="{% url 'films' %}">Films</a>
                &bull;
                <a href="{% url 'artistes' %}">Artistes</a>
                &bull;
                <a href="{% url 'genres' %}">Genres</a>
                &bull;
                <a href="{% url 'nationalites' %}">Nationalités</a>
                &bull;
                <a href="{% url 'personnages' %}">Personnages</a>
                &bull;
                <a href="{% url 'incarnerpersonnages' %}">Incarnations</a>
                <span class="u-pull-right">
                    <a href="{% url 'haystack_search' %}">Recherche</a>
                    &bull;
                    {% if user.is_authenticated %}
                        Connecté en tant que {{ user.username }}. <a href="{% url 'django.contrib.auth.views.logout_then_login' %}">Se déconnecter</a>
                    {% else %}
                        <a href="{% url 'accounts/register' %}">Créer un compte</a>
                        &bull;
                        <a href="{% url 'django.contrib.auth.views.login' %}">Se connecter</a>
                    {% endif %}
                </span>
            </div>
            <div class="row">
                <hr/>
            </div>
            <div class="row">
                {% block content %}{% endblock %}
            </div>
            <div class="row">
                <hr/>
                <div style="text-align:center">
                    À l'huile ciné ! Project by David & Lisa. Copyright 2015. All rights reserved, lol.
                </div>
            </div>
        </div>
    </body>
</html>

django/alhuilecine/siteweb/templates/siteweb/film.html
{% extends "siteweb/base.html" %}

{% block content %}

{% load siteweb_extras %}
{% load staticfiles %}

<img src="{% static "films" %}/{{film.titre}}.jpg" alt="Ce film n'a pas encore d'affiche" style="float:right" width=300px>
<h1>{{ film.titre }}
    {% if user.is_authenticated %}
    <span style="font-size: 2.4rem">
        (
        <a href="{% url 'mettreajour/film' film.id %}">mettre à jour</a>
        &bull;
        <a href="{% url 'supprimer/film' film.id %}">supprimer</a>
        )
    </span>
    {% endif %}
</h1>

<p>Moyenne des notes : {% if avg %}{{ avg|floatformat }}{% else %}Pas encore de notes{% endif %}<br/>
{% if user.is_authenticated %}
	{% if noteDejaAjoutee %}
		<a href="{% url 'mettreajour/noter' noteDejaAjoutee.0.id %}">Modifier votre note</a>
	{% else %}
		<a href="{% url 'ajouter/noter' film.id %}">Noter ce film</a>
	{% endif %}
{% endif %}
</p>

<p>Date de sortie : {{ film.datesortie }}</p>
<p>Genre(s) : {% for genre in film.genres.all %}<a href="{% url 'genre' genre.id %}">{{genre.nom}}</a>{% if not forloop.last %}, {% endif %}{% endfor %}</p>
<p>Nationalité(s) : {% for nationalite in film.nationalites.all %}<a href="{% url 'nationalite' nationalite.id %}">{{nationalite.nom}}</a>{% if not forloop.last %}, {% endif %}{% endfor %}</p>
<p>Acteur(s) : {% for acteur in film.acteurs.all %}<a href="{% url 'artiste' acteur.id %}">{{acteur.prenom}} {{acteur.nom}}</a>{% if not forloop.last %}, {% endif %}{% endfor %}</p>
<p>Réalisateur(s) : {% for realisateur in film.realisateurs.all %}<a href="{% url 'artiste' realisateur.id %}">{{realisateur.prenom}} {{realisateur.nom}}</a>{% if not forloop.last %}, {% endif %}{% endfor %}</p>
<p>Incarnation(s) : {% for incarnerpersonnage in film.incarnerpersonnage_set.all %}<a href="{% url 'personnage' incarnerpersonnage.personnage.id %}">{{incarnerpersonnage.personnage.nom}}</a> joué par <a href="{% url 'artiste' incarnerpersonnage.artiste.id %}">{{incarnerpersonnage.artiste.prenom}} {{incarnerpersonnage.artiste.nom}}</a>{% if not forloop.last %}, {% endif %}{% endfor %}</p>
<p>Synopsis : {{ film.synopsis }}</p>



<h3 style="text-align:center">Forum</h3>
<a href="{% url 'ajouter/message' film.forum.id %}">Poster un message</a>
<br/>
<br/>
{% for messageindente in forummessagesindentes %}
    <div class="row" style="margin-left:{{ messageindente.indentation }}em">
        <u>Message de {{ messageindente.message.envoyeur }} le {{ messageindente.message.dateenvoi }}</u><br/>
        {{ messageindente.message.texte }}
    </div>
    <div class="row" style="margin-left:{{ messageindente.indentation }}em">
    	<a href="{% url 'ajouter/message' film.forum.id messageindente.message.id %}">Répondre</a>
    </div>
    <br/>
{% endfor %}

{% endblock %}

django/alhuilecine/siteweb/templates/siteweb/genre.html
{% extends "siteweb/base.html" %}

{% block content %}

<h1>{{ genre.nom }}
    {% if user.is_authenticated %}
    <span style="font-size: 2.4rem">
        (
        <a href="{% url 'mettreajour/genre' genre.id %}">mettre à jour</a>
        &bull;
        <a href="{% url 'supprimer/genre' genre.id %}">supprimer</a>
        )
    </span>
    {% endif %}
</h1>
<p>Film(s) : {% for film in genre.film_set.all %}<a href="{% url 'film' film.id %}">{{film.titre}}</a>{% if not forloop.last %}, {% endif %}{% endfor %}</p>

{% endblock %}

django/alhuilecine/siteweb/templates/siteweb/genres.html
{% extends "siteweb/base.html" %}

{% block content %}

<h1>Genres
    {% if user.is_authenticated %}
    <span style="font-size: 2.4rem">
        (
        <a href="{% url 'ajouter/genre' %}">ajouter un genre</a>
        )
    </span>
    {% endif %}
</h1>
<table class="u-full-width">
    <thead>
        <tr>
            <th>Nom</th>
        </tr>
    </thead>
    <tbody>
        {% for genre in genres %}
        <tr>
            <th><a href="{% url 'genre' genre.id %}">{{ genre.nom }}</a></th>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

django/alhuilecine/siteweb/templates/siteweb/incarnerpersonnage.html
{% extends "siteweb/base.html" %}

{% block content %}

<h1>Incarnation
    {% if user.is_authenticated %}
    <span style="font-size: 2.4rem">
        (
        <a href="{% url 'mettreajour/incarnerpersonnage' incarnerpersonnage.id %}">mettre à jour</a>
        &bull;
        <a href="{% url 'supprimer/incarnerpersonnage' incarnerpersonnage.id %}">supprimer</a>
        )
    </span>
    {% endif %}
</h1>
<p>Le personnage <a href="{% url 'personnage' incarnerpersonnage.personnage.id %}">{{ incarnerpersonnage.personnage.nom }}</a> est incarné par l'acteur <a href="{% url 'artiste' incarnerpersonnage.artiste.id %}">{{ incarnerpersonnage.artiste.prenom }} {{ incarnerpersonnage.artiste.nom }}</a> dans le film <a href="{% url 'film' incarnerpersonnage.film.id %}">{{ incarnerpersonnage.film.titre }}</a>.</p>

{% endblock %}

django/alhuilecine/siteweb/templates/siteweb/incarnerpersonnages.html
{% extends "siteweb/base.html" %}

{% block content %}

<h1>Incarnations
    {% if user.is_authenticated %}
    <span style="font-size: 2.4rem">
        (
        <a href="{% url 'ajouter/incarnerpersonnage' %}">ajouter une incarnation</a>
        )
    </span>
    {% endif %}
</h1>
<table class="u-full-width">
    <thead>
        <tr>
            <th>Personnage</th>
            <th>Acteur</th>
            <th>Film</th>
            {% if user.is_authenticated %}
            <th>Opérations</th>
            {% endif %}
        </tr>
    </thead>
    <tbody>
        {% for incarnerpersonnage in incarnerpersonnages %}
        <tr>
            <th><a href="{% url 'personnage' incarnerpersonnage.personnage.id %}">{{ incarnerpersonnage.personnage.nom }}</a></th>
            <th><a href="{% url 'artiste' incarnerpersonnage.artiste.id %}">{{ incarnerpersonnage.artiste.nom }}</a></th>
            <th><a href="{% url 'film' incarnerpersonnage.film.id %}">{{ incarnerpersonnage.film.titre }}</a></th>
            {% if user.is_authenticated %}
            <th><a href="{% url 'mettreajour/incarnerpersonnage' incarnerpersonnage.id %}">Mettre à jour</a> &bull; <a href="{% url 'supprimer/incarnerpersonnage' incarnerpersonnage.id %}">Supprimer</a> </th>
            {% endif %}
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

django/alhuilecine/siteweb/templates/siteweb/index.html
{% extends "siteweb/base.html" %}

{% block content %}

<p>
Bienvenue sur <i>À l'huile ciné !</i>, une base de données en ligne qui référence films, acteurs, réalisateurs, et bien plus encore !<br/><br/>
Vous pouvez utiliser les liens ci-dessus pour naviguer dans la base de données. N'hésitez pas à vous enregistrer pour profiter d'encore de fonctionnalités :)
</p>

{% endblock %}

django/alhuilecine/siteweb/templates/siteweb/login.html
{% extends "siteweb/base.html" %}

{% block content %}

{% if form.errors %}
<p>Votre nom d'utilisateur et votre mot de passe sont incorrects. Veuillez essayer de nouveau.</p>
{% endif %}

<form method="post" action="{% url 'django.contrib.auth.views.login' %}">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="login" />
<input type="hidden" name="next" value="{{ next }}" />
</form>

{% endblock %}

django/alhuilecine/siteweb/templates/siteweb/nationalite.html
{% extends "siteweb/base.html" %}

{% block content %}

<h1>{{ nationalite.nom }}
    {% if user.is_authenticated %}
    <span style="font-size: 2.4rem">
        (
        <a href="{% url 'mettreajour/nationalite' nationalite.id %}">mettre à jour</a>
        &bull;
        <a href="{% url 'supprimer/nationalite' nationalite.id %}">supprimer</a>
        )
    </span>
    {% endif %}
</h1>
<p>Artiste(s) : {% for artiste in nationalite.artiste_set.all %}<a href="{% url 'artiste' artiste.id %}">{{artiste.prenom}} {{artiste.nom}}</a>{% if not forloop.last %}, {% endif %}{% endfor %}</p>
<p>Film(s) : {% for film in nationalite.film_set.all %}<a href="{% url 'film' film.id %}">{{film.titre}}</a>{% if not forloop.last %}, {% endif %}{% endfor %}</p>

{% endblock %}

django/alhuilecine/siteweb/templates/siteweb/nationalites.html
{% extends "siteweb/base.html" %}

{% block content %}

<h1>Nationalités
    {% if user.is_authenticated %}
    <span style="font-size: 2.4rem">
        (
        <a href="{% url 'ajouter/nationalite' %}">ajouter une nationalité</a>
        )
    </span>
    {% endif %}
</h1>
<table class="u-full-width">
    <thead>
        <tr>
            <th>Nom</th>
        </tr>
    </thead>
    <tbody>
        {% for nationalite in nationalites %}
        <tr>
            <th><a href="{% url 'nationalite' nationalite.id %}">{{ nationalite.nom }}</a></th>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

django/alhuilecine/siteweb/templates/siteweb/personnage.html
{% extends "siteweb/base.html" %}

{% block content %}

<h1>{{ personnage.nom }}
    {% if user.is_authenticated %}
    <span style="font-size: 2.4rem">
        (
        <a href="{% url 'mettreajour/personnage' personnage.id %}">mettre à jour</a>
        &bull;
        <a href="{% url 'supprimer/personnage' personnage.id %}">supprimer</a>
        )
    </span>
    {% endif %}
</h1>
<p>Incarnation(s) : {% for incarnerpersonnage in personnage.incarnerpersonnage_set.all %}<a href="{% url 'artiste' incarnerpersonnage.artiste.id %}">{{incarnerpersonnage.artiste.prenom}} {{incarnerpersonnage.artiste.nom}}</a> dans <a href="{% url 'film' incarnerpersonnage.film.id %}">{{incarnerpersonnage.film.titre}}</a>{% if not forloop.last %}, {% endif %}{% endfor %}</p>

{% endblock %}

django/alhuilecine/siteweb/templates/siteweb/personnages.html
{% extends "siteweb/base.html" %}

{% block content %}

<h1>Personnages
    {% if user.is_authenticated %}
    <span style="font-size: 2.4rem">
        (
        <a href="{% url 'ajouter/personnage' %}">ajouter un personnage</a>
        )
    </span>
    {% endif %}
</h1>
<table class="u-full-width">
    <thead>
        <tr>
            <th>Nom</th>
        </tr>
    </thead>
    <tbody>
        {% for personnage in personnages %}
        <tr>
            <th><a href="{% url 'personnage' personnage.id %}">{{ personnage.nom }}</a></th>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

django/alhuilecine/siteweb/templates/siteweb/register.html
{% extends "siteweb/base.html" %}

{% block content %}

<h1>Création d'un compte</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Valider"/>
</form>

{% endblock %}